# kubectl create -f kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
 name: sezam.web
 labels:
   app: sezam.web
spec:
 replicas: 2
 selector:
   matchLabels:
     app: sezam.web
 template: