FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build-env
WORKDIR /src
COPY . ./
RUN dotnet restore Telnet/Sezam.Telnet.csproj
RUN dotnet publish Telnet/Sezam.Telnet.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/runtime:10.0
WORKDIR /app
COPY --from=build-env /out/ ./

ENV DOTNET_ENVIRONMENT=Production
EXPOSE 2023

ENTRYPOINT ["/app/Sezam.Telnet"]
