// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sezam.Data;

#nullable disable

namespace Sezam.Data.Migrations
{
    [DbContext(typeof(SezamDbContext))]
    [Migration("20260724132512_AddPrivateMessage")]
    partial class AddPrivateMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sezam.Data.EF.ConfMessage", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Filename")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("MsgNo")
                        .HasColumnType("int");

                    b.Property<byte[]>("ParentMessageId")
                        .HasColumnType("binary(16)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Filename");

                    b.HasIndex("ParentMessageId");

                    b.HasIndex("Time");

                    b.HasIndex("TopicId", "MsgNo");

                    b.HasIndex("AuthorId", "TopicId", "MsgNo");

                    b.HasIndex("TopicId", "AuthorId", "MsgNo");

                    b.ToTable("ConfMessages");
                });

            modelBuilder.Entity("Sezam.Data.EF.ConfTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ConferenceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("NextSequence")
                        .HasColumnType("int");

                    b.Property<int?>("RedirectToId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TopicNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RedirectToId");

                    b.HasIndex("ConferenceId", "Name")
                        .IsUnique();

                    b.HasIndex("ConferenceId", "TopicNo")
                        .IsUnique();

                    b.ToTable("ConfTopics");
                });

            modelBuilder.Entity("Sezam.Data.EF.Conference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VolumeNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name", "VolumeNo")
                        .IsUnique();

                    b.ToTable("Conferences");
                });

            modelBuilder.Entity("Sezam.Data.EF.MessageText", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MessageTexts");
                });

            modelBuilder.Entity("Sezam.Data.EF.PrivateMessage", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("binary(16)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("MessageTextId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<DateTime?>("ReadTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MessageTextId")
                        .IsUnique();

                    b.HasIndex("SentTime");

                    b.HasIndex("RecipientId", "ReadTime");

                    b.HasIndex("SenderId", "SentTime");

                    b.ToTable("PrivateMessages");
                });

            modelBuilder.Entity("Sezam.Data.EF.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AreaCode")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("City")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Company")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime?>("LastCall")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("MemberSince")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PaidUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("PostCode")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<int>("Roles")
                        .HasColumnType("int");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Username")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("LastCall");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sezam.Data.EF.UserConf", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ConferenceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ConferenceId");

                    b.HasIndex("ConferenceId")
                        .IsUnique();

                    b.ToTable("UserConf");
                });

            modelBuilder.Entity("Sezam.Data.EF.UserTopic", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("TopicId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("SeenTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UserId", "TopicId");

                    b.HasIndex("TopicId")
                        .IsUnique();

                    b.ToTable("UserTopic");
                });

            modelBuilder.Entity("Sezam.Data.EF.ConfMessage", b =>
                {
                    b.HasOne("Sezam.Data.EF.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sezam.Data.EF.MessageText", "MessageText")
                        .WithOne()
                        .HasForeignKey("Sezam.Data.EF.ConfMessage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sezam.Data.EF.ConfMessage", "ParentMessage")
                        .WithMany()
                        .HasForeignKey("ParentMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sezam.Data.EF.ConfTopic", "Topic")
                        .WithMany("Messages")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("MessageText");

                    b.Navigation("ParentMessage");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Sezam.Data.EF.ConfTopic", b =>
                {
                    b.HasOne("Sezam.Data.EF.Conference", "Conference")
                        .WithMany("ConfTopics")
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sezam.Data.EF.ConfTopic", "RedirectTo")
                        .WithMany()
                        .HasForeignKey("RedirectToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Conference");

                    b.Navigation("RedirectTo");
                });

            modelBuilder.Entity("Sezam.Data.EF.PrivateMessage", b =>
                {
                    b.HasOne("Sezam.Data.EF.MessageText", "MessageText")
                        .WithOne()
                        .HasForeignKey("Sezam.Data.EF.PrivateMessage", "MessageTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sezam.Data.EF.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sezam.Data.EF.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageText");

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Sezam.Data.EF.UserConf", b =>
                {
                    b.HasOne("Sezam.Data.EF.Conference", "Conference")
                        .WithOne("UserConf")
                        .HasForeignKey("Sezam.Data.EF.UserConf", "ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sezam.Data.EF.User", "User")
                        .WithMany("UserConfs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conference");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sezam.Data.EF.UserTopic", b =>
                {
                    b.HasOne("Sezam.Data.EF.ConfTopic", null)
                        .WithOne("UserTopic")
                        .HasForeignKey("Sezam.Data.EF.UserTopic", "TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sezam.Data.EF.User", null)
                        .WithMany("UserTopics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sezam.Data.EF.ConfTopic", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("UserTopic");
                });

            modelBuilder.Entity("Sezam.Data.EF.Conference", b =>
                {
                    b.Navigation("ConfTopics");

                    b.Navigation("UserConf");
                });

            modelBuilder.Entity("Sezam.Data.EF.User", b =>
                {
                    b.Navigation("UserConfs");

                    b.Navigation("UserTopics");
                });
#pragma warning restore 612, 618
        }
    }
}
