//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sezam {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sezam.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не постоји тема {0}.
        /// </summary>
        internal static string Conf_UnknownTopic {
            get {
                return ResourceManager.GetString("Conf_UnknownTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здраво рођаци.
        /// </summary>
        internal static string ConnectedBanner {
            get {
                return ResourceManager.GetString("ConnectedBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESC to stop.
        /// </summary>
        internal static string EscToStop {
            get {
                return ResourceManager.GetString("EscToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тачно време је: {0: HH:mm:ss dd MMMM yyyy}.
        /// </summary>
        internal static string Root_Time {
            get {
                return ResourceManager.GetString("Root_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unete šifre se ne podudaraju.
        /// </summary>
        internal static string Set_Msg_PasswordsMismatch {
            get {
                return ResourceManager.GetString("Set_Msg_PasswordsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutno važeća šifra.
        /// </summary>
        internal static string Set_Prompt_CurrentPassword {
            get {
                return ResourceManager.GetString("Set_Prompt_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova šifra.
        /// </summary>
        internal static string Set_Prompt_NewPassword {
            get {
                return ResourceManager.GetString("Set_Prompt_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda šifre.
        /// </summary>
        internal static string Set_Prompt_VerifyPassword {
            get {
                return ResourceManager.GetString("Set_Prompt_VerifyPassword", resourceCulture);
            }
        }
    }
}
