//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sezam.Commands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sezam.Commands.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resigned from topic {0}.
        /// </summary>
        internal static string Conf_Resigned {
            get {
                return ResourceManager.GetString("Conf_Resigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resigned from conf {0}.
        /// </summary>
        internal static string Conf_TopicResigned {
            get {
                return ResourceManager.GetString("Conf_TopicResigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic {0} does not exist.
        /// </summary>
        internal static string Conf_UnknownTopic {
            get {
                return ResourceManager.GetString("Conf_UnknownTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to conf {0}.
        /// </summary>
        internal static string Conf_Welcome {
            get {
                return ResourceManager.GetString("Conf_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello relatives.
        /// </summary>
        internal static string ConnectedBanner {
            get {
                return ResourceManager.GetString("ConnectedBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye now..
        /// </summary>
        internal static string Root_Bye {
            get {
                return ResourceManager.GetString("Root_Bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hangup?No/Yes.
        /// </summary>
        internal static string Root_Bye_Prompt {
            get {
                return ResourceManager.GetString("Root_Bye_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current time is: {0: HH:mm:ss dd MMMM yyyy}.
        /// </summary>
        internal static string Root_Time {
            get {
                return ResourceManager.GetString("Root_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}, your last visit was {1:dd MMM yyyy}.
        /// </summary>
        internal static string Root_WelcomeUser {
            get {
                return ResourceManager.GetString("Root_WelcomeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current language: {0}.
        /// </summary>
        internal static string Set_Lang_ShowCurrent {
            get {
                return ResourceManager.GetString("Set_Lang_ShowCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language preference updated to: {0} ({1}).
        /// </summary>
        internal static string Set_LangUpdated {
            get {
                return ResourceManager.GetString("Set_LangUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        internal static string Set_Msg_PasswordsMismatch {
            get {
                return ResourceManager.GetString("Set_Msg_PasswordsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed..
        /// </summary>
        internal static string Set_Password_Changed {
            get {
                return ResourceManager.GetString("Set_Password_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string Set_Prompt_CurrentPassword {
            get {
                return ResourceManager.GetString("Set_Prompt_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string Set_Prompt_NewPassword {
            get {
                return ResourceManager.GetString("Set_Prompt_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Password.
        /// </summary>
        internal static string Set_Prompt_VerifyPassword {
            get {
                return ResourceManager.GetString("Set_Prompt_VerifyPassword", resourceCulture);
            }
        }
    }
}
